services:
  frontend:
    image: node:lts
    container_name: frontend-farm
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: npm run dev

  postgres:
    image: postgres:latest
    container_name: postgres-farm
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres-farm-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-farm
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    volumes:
      - pgadmin-farm-data:/var/lib/pgadmin

volumes:
  postgres-farm-data:
    external: true
  pgadmin-farm-data:
    external: true