# Generated by Django 5.1 on 2024-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Betail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('MALE', 'male'), ('FEMELLE', 'femelle')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('date_entre_farm', models.DateField()),
                ('mere_tag', models.CharField(max_length=20)),
                ('pere_tag', models.CharField(max_length=20)),
            ],
        ),
    ]
