# Generated by Django 5.1 on 2024-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
