# Generated by Django 5.1 on 2024-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_calendrier_end_alter_calendrier_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
