# Generated by Django 5.1 on 2024-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240825_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betail',
            name='sexe',
            field=models.CharField(choices=[('male', 'Male'), ('femelle', 'Femelle')], max_length=10),
        ),
    ]
